### ISSUE TITLE
v0.0.1 release, with some API docs?

### ISSUE THREAD

**Issue by mcandre** [signalspec/signalspec#3]
Cool initiative!

I like how we're now blending ideas from parsers, protocol specs, and even FPGA communication. Abstract and practical at the same time.

You mentioned earlier that signalspec will have support for querying the current line number during processing. I would be delighted to see API documentation for this published to the docs.rs site. Then I would feel more confident in perhaps rewriting my PEG grammar in signalspec.

https://docs.rs/signalspec/latest/signalspec/index.html

**Comment by kevinmehall** [comment]
The parser for the Signalspec language is implemented using rust-peg and [its grammar](https://github.com/signalspec/signalspec/blob/master/src/syntax/grammar.rs) serves as a good example of using rust-peg to construct [an AST](https://github.com/signalspec/signalspec/blob/master/src/syntax/ast.rs) with error recovery and spans recording the position of each node. The code that uses the line index to map byte positions to line numbers is actually in [codespan-reporting](https://docs.rs/codespan-reporting/latest/codespan_reporting/files/index.html), via the trait implementation [here](https://github.com/signalspec/signalspec/blob/master/cli/diagnostic.rs) to produce messages like this from the positions in the AST:

```console
$ cargo run -p signalspec_cli -- -t tests/check-fail/global-undefined-variable.signalspec
error: undefined variable `zzzz`
  ┌─ tests/check-fail/global-undefined-variable.signalspec:2:9
  │
2 │ let y = zzzz
  │         ^^^^ not found
```

While code written in Signalspec has some ability to parse text, its underlying theory is more closely related to regular expressions than any parsing formalism like PEG that can handle recursive structures, so it's not really something you'd use in place of rust-peg. While there will likely be a Rust API for invoking Signalspec code published to crates.io in due time, it's not really a Rust library, but a programming language of its own. So if I understand what you're trying to do correctly, you probably want to use it for inspiration and examples for rust-peg and codespan-reporting rather than use it directly as a library.
